import axios from "axios";

export async function generateResume(details: any): Promise<string> {
  const prompt = `Create a clean, professional, and visually appealing resume using the following details: ${JSON.stringify(details)}`;
  const apiKey = process.env.REACT_APP_GEMINI_API_KEY;

  if (!apiKey) throw new Error("Google Gemini API key not found.");

  const response = await axios.post(
    "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent",
    {
      contents: [
        {
          role: "user",
          parts: [{ text: prompt }]
        }
      ]
    },
    {
      headers: {
        "Content-Type": "application/json",
        "X-goog-api-key": apiKey
      }
    }
  );

  const generatedText = response.data?.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!generatedText) throw new Error("No content generated by Gemini API");
  return generatedText;
}
